### ISSUE TITLE
Textures missing 

### ISSUE THREAD

**Issue by DatOnePlayer** [whert-dev/mindustry-whert-tex#1]
The flash silicon smelter's textures is missing

**Comment by DatOnePlayer** [comment]
Also the oil power generator is not on the tech tree

**Comment by kapzduke** [comment]
The oil burner ((currently)) does not exist. It has no .json file, nor does it have a texture. There isn't even a /power folder in /content. It does exist in the bundle.properties file, however

**Comment by whert-dev** [comment]
Comrades, thanks for your responsibility. Sorry for long delay, i had some problems. I've just fixed everything, i suppose.
